Add a charmcraft.yaml, and remove EOL groovy series
juju-solutions/charm-ubuntu pull request #41
Opened 2021-11-04 09:44 UTC by mthaddon

Charms now need a charmcraft.yaml file to define what series to build on and for. 

Also remove `groovy`, which is EOL since July 2021.

2022-02-02 14:54 UTC, johnsca approved these changes

2022-02-02 15:00 UTC, johnsca requested changes
Actually, groovy and hirsute are still [used in the integration test](https://github.com/juju-solutions/charm-ubuntu/blob/89a3e4cf86490b231ae040979e1e7676246b33a0/tests/integration/test_charm.py#L26-L27), so that should be updated as well.

2022-03-01 19:58 UTC, addyess commented
@mthaddon , could you add
```tests/data/model-config.yaml``` with the contents:

```yaml
---
image-stream: daily
```

after that update the tox.ini use the `--model-config` option i'm adding to [`pytest-operator`](https://github.com/charmed-kubernetes/pytest-operator/pull/53).  Hopefully i'll get it reviewed and added soon

```
[testenv:integration]
deps =
    pytest
    pytest-operator
    ipdb
commands = pytest --tb native --show-capture=no --log-cli-level=INFO -s --disable-warnings --model-config tests/data/model-config.yam {posargs} {toxinidir}/tests/integration
```

2022-03-04 12:12 UTC, kwmonroe approved these changes

2022-03-04 12:12 UTC, merged